dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank

jobs:
  include:
    - stage: build and publish
      language: java
      jdk: openjdk11
      addons:
        mariadb: '10.2'
      install: skip
      before_script:
        - mysql -uroot < databases/tracker/create_databases.sql
        - curl https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.1.1/flyway-commandline-5.1.1-linux-x64.tar.gz | tar xvz
        - flyway-*/flyway -url="jdbc:mysql://localhost:3306/tracker_test" -locations=filesystem:databases/tracker -user=tracker -password= clean migrate
      script: ./gradlew clean build
      before_install:
        - pwd
        - ls -la
        - chmod +x ./gradlew
      before_deploy:
        - git config --local user.name "pushpa89"
        - git config --local user.email "pushpalatha.s@cognizant.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: d1d6ddfba16e6c2c2d779855815e5a49d79f77f7
        file: "build/libs/pal-tracker.jar"
        skip_cleanup: true
    - stage: deploy to cf
      language: java
      before_install:
        - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        - sudo apt-get update
        - sudo apt-get install cf-cli
        - sudo apt-get -y install jq
        - curl https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.1.1/flyway-commandline-5.1.1-linux-x64.tar.gz | tar xvz
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P build/libs https://github.com/pushpa89/pal-tracker/releases/download/$RELEASE_TAG/pal-tracker.jar
      before_deploy:
        - echo "Deploying $RELEASE_TAG to Cloud Foundry"
      before_script:
        - cf login -a $CF_API_URL -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
        - scripts/migrate-databases.sh pal-tracker .
      deploy:
        provider: cloudfoundry
        api: https://pal-tracker-insightful-echidna-wz.cfapps.io/
        username: pushpalatha.s@cognizant.com
        password: Pushpa_1989
        organization: springassignment
        space: development
