dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank


jobs:
  include:
    - stage: build and publish
      language: java
      jdk: openjdk11
      install: skip
      script: ./gradlew clean build
      before_install:
        - pwd
        - ls -la
        - chmod +x ./gradlew
      before_deploy:
        - git config --local user.name "pushpa89"
        - git config --local user.email "pushpalatha.s@cognizant.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: e8c9b0efa35f81b76845eb7893a24442de31c1a1
        file: "build/libs/pal-tracker.jar"
        skip_cleanup: true
    - stage: deploy to cf
      language: bash
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P build/libs https://github.com/pushpa89/pal-tracker/releases/download/$RELEASE_TAG/pal-tracker.jar
      before_deploy:
        - echo "Deploying $RELEASE_TAG to Cloud Foundry"
      deploy:
        provider: cloudfoundry
        api: https://pal-tracker-insightful-echidna-wz.cfapps.io/
        username: pushpalatha.s@cognizant.com
        password: Pushpa_1989
        organization: springassignment
        space: development
